os: linux
dist: xenial
language: shell
jobs:
    include:
        - stage: rush build && heft test
          script:
              - set -e

              - echo 'Installing build toolchain...' && echo -en 'travis_fold:start:install\\r'
              - sudo apt update
              - sudo apt -y nodejs node-typescript eslint
              - echo -en 'travis_fold:end:install\\r'

              - echo 'Building projects in monorepo...' && echo -en 'travis_fold:start:build\\r'
              - npm i
              - npm run build
              - echo -en 'travis_fold:end:build\\r'

              - echo 'Testing package...' && echo -en 'travis_fold:start:test\\r'
              - npm run test
              - echo -en 'travis_fold:end:test\\r'

              - echo 'All application tests run successfully'
