os: linux
dist: xenial
language: node_js
node_js:
    - '14.16.0'
jobs:
    include:
        - stage: rush build && heft test
          script:
              - set -e

              - echo 'Installing build toolchain...' && echo -en 'travis_fold:start:install\\r'
              - sudo apt update
              - sudo apt install -y node-typescript
              - echo -en 'travis_fold:end:install\\r'

              - echo 'Linting project...' && echo -en 'travis_fold:start:lint\\r'
              - npm install -g eslint jest
              - npm run lint
              - echo -en 'travis_fold:end:lint\\r'

              - echo 'Building project...' && echo -en 'travis_fold:start:build\\r'
              - npm i
              - npm run build
              - echo -en 'travis_fold:end:build\\r'

              - echo 'Testing package...' && echo -en 'travis_fold:start:test\\r'
              - npm run test
              - echo -en 'travis_fold:end:test\\r'

              - echo 'All application tests run successfully'
